package com.example.homeworkuri

import com.example.homeworkuri.UiItem.TitleItem
import com.example.homeworkuri.UiItem.SiteData

object Server {
    fun getSites(): List<UiItem> = listOf(
        TitleItem("Новости:"),
        SiteData("https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Lenta.svg/1280px-Lenta.svg.png",
        "Lenta.ru",
        "https://lenta.ru"),
        SiteData("https://cdnn21.img.ria.ru//i/export/ria/logo.png",
        "РИА \"Новости\"",
        "https://ria.ru/"),
        SiteData("https://avatars.githubusercontent.com/u/828722?s=280&v=4",
        "BBC",
        "https://www.bbc.com/"),
        SiteData("https://m.media-amazon.com/images/I/41sa7YauzhL.jpg",
        "The Times",
        "https://www.thetimes.co.uk/"),
        SiteData("https://upload.wikimedia.org/wikipedia/commons/f/f3/Logo-onliner-by.png",
        "Onliner",
        "https://www.onliner.by/"),
        TitleItem("Социальные сети:"),
        SiteData("https://img2.freepng.ru/20180803/vtg/kisspng-logo-brand-instagram-social-media-photography-albi-5b64fd27b37ec9.0345744115333450637352.jpg",
            "Instagram",
            "https://www.instagram.com/"),
        SiteData("https://sun9-31.userapi.com/impg/g5lmrQqp5KRMRttAidcs45QQMcUJANZEqiD2iA/7Pcfo_WmTXE.jpg?size=807x454&quality=96&sign=a00555a605550e98732d34fee724cfc9&type=album",
            "Вконтакте",
            "https://vk.com"),
        SiteData("https://cybersport.metaratings.ru/storage/images/d2/bc/d2bc4db1330944cc226803c06cc27129.jpg",
            "TikTok",
            "https://www.tiktok.com/"),
        SiteData("http://lluban.by/images/storage/news/000479_98349_big.png",
            "Viber",
            "https://www.viber.com/ru/"),
        SiteData("https://blog.waalaxy.com/wp-content/uploads/2021/01/Linkedin-Logo.png",
            "Linkedin",
            "https://ru.linkedin.com/"),
        TitleItem("Фильмы:"),
        SiteData("https://res.cloudinary.com/admitad-gmbh/image/upload/v1662639448/yswnfysiidlsiw9usxsn.png",
            "Кинопоиск",
            "https://www.kinopoisk.ru/"),
        SiteData("https://upload.wikimedia.org/wikipedia/ru/5/5b/Иви-лого.png",
            "Иви",
            "https://www.ivi.ru/"),
        SiteData("https://cdn.cookielaw.org/logos/dd6b162f-1a32-456a-9cfe-897231c7763c/4345ea78-053c-46d2-b11e-09adaef973dc/Netflix_Logo_PMS.png",
            "Netflix",
            "https://www.netflix.com/by-ru/"),
        SiteData("https://brand.amediateka.ru/img/images/logo1.png",
            "Amediateka",
            "https://www.amediateka.ru/"),
        SiteData("https://i.pcmag.com/imagery/reviews/06Oau8UJO0of0q2R98bMSZ5-6.fit_scale.size_760x427.v1590600630.png",
            "Hbo max",
            "https://www.hbomax.com"),
        TitleItem("Другие:"),
        SiteData("https://content.presspage.com/uploads/2658/c800_logo-stackoverflow-square.jpg?98978",
            "stack overflow",
            "https://stackoverflow.com/"),
        SiteData("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQld6JVAB0v7u-8X9H9p8YmGp2E1IKIk9h6twBuai8YS0LlyB35R6LnwjIHB64vWEKBuw&usqp=CAU",
            "Яндекс",
            "https://yandex.by/"),
        SiteData("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1280px-Google_2015_logo.svg.png",
            "Google",
            "https://www.google.ru/"),
        SiteData("https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png",
            "GitHub ",
            "https://github.com/"),
    )
}